apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/name: announcements
    app.kubernetes.io/component: app
data:
  PGHOST: postgres-service
  PGPORT: "5432"
  PGDATABASE: announcements
