apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/name: announcements
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: ann_user
  POSTGRES_PASSWORD: ann_pass
