apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  labels:
    app: nextcloud
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  NEXTCLOUD_UPDATE: '1'
  NEXTCLOUD_ADMIN_USER: "any_name_you_want"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"
  POSTGRES_HOST: "postgres-service"
